import xlwt
import time
import logic
import json
import requests

main = logic.Field()

style0 = xlwt.easyxf('font: name Arial, color-index black, bold on; align: wrap on, vert centre')

wb = xlwt.Workbook()
ws = wb.add_sheet('Test Sheet',cell_overwrite_ok=True)
#---------------------------------
ws.write(0,0,'Ball',style0)
ws.write(0,2,'Object Center',style0)
ws.write(0,3,'X',style0)
ws.write(1,3,'Y',style0)
ws.write(2,2,'Bounding Box',style0)
ws.write(2,3,'X Left',style0)
ws.write(3,3,'Y Top',style0)
ws.write(4,3,'X Right',style0)
ws.write(5,3,'Y Bottom',style0)
ws.write(6,3,'Area',style0)
ws.write(7,3,'Orientation',style0)
ws.write(8,3,'Aspect Ratio',style0)
ws.write(9,3,'Nb Holes',style0)
#---------------------------------
ws.write(10,0,'Corners',style0)
ws.write(10,3,'X',style0)
ws.write(11,3,'Y',style0)
ws.write(12,3,'X',style0)
ws.write(13,3,'Y',style0)
ws.write(14,3,'X',style0)
ws.write(15,3,'Y',style0)
ws.write(16,3,'X',style0)
ws.write(17,3,'Y',style0)
#---------------------------------
ws.write(18,0,'Red Team',style0)
#
ws.write(18,1,'Circle',style0)
ws.write(18,2,'Object Center',style0)
ws.write(18,3,'X',style0)
ws.write(19,3,'Y',style0)
ws.write(20,2,'Bounding Box',style0)
ws.write(20,3,'X Left',style0)
ws.write(21,3,'Y Top',style0)
ws.write(22,3,'X Right',style0)
ws.write(23,3,'Y Bottom',style0)
ws.write(24,3,'Area',style0)
ws.write(25,3,'Orientation',style0)
ws.write(26,3,'Aspect Ratio',style0)
ws.write(27,3,'Nb Holes',style0)
#
ws.write(28,1,'Square',style0)
ws.write(28,2,'Object Center',style0)
ws.write(28,3,'X',style0)
ws.write(29,3,'Y',style0)
ws.write(30,2,'Bounding Box',style0)
ws.write(30,3,'X Left',style0)
ws.write(31,3,'Y Top',style0)
ws.write(32,3,'X Right',style0)
ws.write(33,3,'Y Bottom',style0)
ws.write(34,3,'Area',style0)
ws.write(35,3,'Orientation',style0)
ws.write(36,3,'Aspect Ratio',style0)
ws.write(37,3,'Nb Holes',style0)
#
ws.write(38,1,'Triangle',style0)
ws.write(38,2,'Object Center',style0)
ws.write(38,3,'X',style0)
ws.write(39,3,'Y',style0)
ws.write(40,2,'Bounding Box',style0)
ws.write(40,3,'X Left',style0)
ws.write(41,3,'Y Top',style0)
ws.write(42,3,'X Right',style0)
ws.write(43,3,'Y Bottom',style0)
ws.write(44,3,'Area',style0)
ws.write(45,3,'Orientation',style0)
ws.write(46,3,'Aspect Ratio',style0)
ws.write(47,3,'Nb Holes',style0)
#---------------------------------
ws.write(48,0,'Blue Team',style0)
#
ws.write(48,1,'Circle',style0)
ws.write(48,2,'Object Center',style0)
ws.write(48,3,'X',style0)
ws.write(49,3,'Y',style0)
ws.write(50,2,'Bounding Box',style0)
ws.write(50,3,'X Left',style0)
ws.write(51,3,'Y Top',style0)
ws.write(52,3,'X Right',style0)
ws.write(53,3,'Y Bottom',style0)
ws.write(54,3,'Area',style0)
ws.write(55,3,'Orientation',style0)
ws.write(56,3,'Aspect Ratio',style0)
ws.write(57,3,'Nb Holes',style0)
#
ws.write(58,1,'Square',style0)
ws.write(58,2,'Object Center',style0)
ws.write(58,3,'X',style0)
ws.write(59,3,'Y',style0)
ws.write(60,2,'Bounding Box',style0)
ws.write(60,3,'X Left',style0)
ws.write(61,3,'Y Top',style0)
ws.write(62,3,'X Right',style0)
ws.write(63,3,'Y Bottom',style0)
ws.write(64,3,'Area',style0)
ws.write(65,3,'Orientation',style0)
ws.write(66,3,'Aspect Ratio',style0)
ws.write(67,3,'Nb Holes',style0)
#
ws.write(68,1,'Triangle',style0)
ws.write(68,2,'Object Center',style0)
ws.write(68,3,'X',style0)
ws.write(69,3,'Y',style0)
ws.write(70,2,'Bounding Box',style0)
ws.write(70,3,'X Left',style0)
ws.write(71,3,'Y Top',style0)
ws.write(72,3,'X Right',style0)
ws.write(73,3,'Y Bottom',style0)
ws.write(74,3,'Area',style0)
ws.write(75,3,'Orientation',style0)
ws.write(76,3,'Aspect Ratio',style0)
ws.write(77,3,'Nb Holes',style0)
#---------------------------------
x=0
y=1
newparsed = ''
while x<5:
    r = requests.get("http://172.16.0.1:8001/FieldData/GetData", timeout=0.5)
    parsed = json.loads(r.text)
    print(parsed["Ball"]["Object Center"]["X"])
    oldparsed = newparsed
    newparsed = parsed["Ball"]["Object Center"]["X"]
    y=1
    while oldparsed==newparsed:
        time.sleep(1)
        r = requests.get("http://172.16.0.1:8001/FieldData/GetData", timeout=0.5)
        parsed = json.loads(r.text)
        print("Data has not changed. ("+str(y)+")")
        oldparsed = newparsed
        newparsed = parsed["Ball"]["Object Center"]["X"]
        y=y+1
    #---------------------------------
    ws.write(0,4+x,parsed["Ball"]["Object Center"]["X"],style0)
    ws.write(1,4+x,parsed["Ball"]["Object Center"]["Y"],style0)
    ws.write(2,4+x,parsed["Ball"]["Bounding Box"]["X Left"],style0)
    ws.write(3,4+x,parsed["Ball"]["Bounding Box"]["Y Top"],style0)
    ws.write(4,4+x,parsed["Ball"]["Bounding Box"]["X Right"],style0)
    ws.write(5,4+x,parsed["Ball"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(6,4+x,parsed["Ball"]["Area"],style0)
    ws.write(7,4+x,parsed["Ball"]["Orientation"],style0)
    ws.write(8,4+x,parsed["Ball"]["Aspect Ratio"],style0)
    ws.write(9,4+x,parsed["Ball"]["Nb Holes"],style0)
    ws.write(10,4+x,parsed["Corners"][0]["X"],style0)
    ws.write(11,4+x,parsed["Corners"][0]["Y"],style0)
    ws.write(12,4+x,parsed["Corners"][1]["X"],style0)
    ws.write(13,4+x,parsed["Corners"][1]["Y"],style0)
    ws.write(14,4+x,parsed["Corners"][2]["X"],style0)
    ws.write(15,4+x,parsed["Corners"][2]["Y"],style0)
    ws.write(16,4+x,parsed["Corners"][3]["X"],style0)
    ws.write(17,4+x,parsed["Corners"][3]["Y"],style0)
    ws.write(18,4+x,parsed["Red Team Data"]["Circle"]["Object Center"]["X"],style0)
    ws.write(19,4+x,parsed["Red Team Data"]["Circle"]["Object Center"]["Y"],style0)
    ws.write(20,4+x,parsed["Red Team Data"]["Circle"]["Bounding Box"]["X Left"],style0)
    ws.write(21,4+x,parsed["Red Team Data"]["Circle"]["Bounding Box"]["Y Top"],style0)
    ws.write(22,4+x,parsed["Red Team Data"]["Circle"]["Bounding Box"]["X Right"],style0)
    ws.write(23,4+x,parsed["Red Team Data"]["Circle"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(24,4+x,parsed["Red Team Data"]["Circle"]["Area"],style0)
    ws.write(25,4+x,parsed["Red Team Data"]["Circle"]["Orientation"],style0)
    ws.write(26,4+x,parsed["Red Team Data"]["Circle"]["Aspect Ratio"],style0)
    ws.write(27,4+x,parsed["Red Team Data"]["Circle"]["Nb Holes"],style0)
    ws.write(28,4+x,parsed["Red Team Data"]["Square"]["Object Center"]["X"],style0)
    ws.write(29,4+x,parsed["Red Team Data"]["Square"]["Object Center"]["Y"],style0)
    ws.write(30,4+x,parsed["Red Team Data"]["Square"]["Bounding Box"]["X Left"],style0)
    ws.write(31,4+x,parsed["Red Team Data"]["Square"]["Bounding Box"]["Y Top"],style0)
    ws.write(32,4+x,parsed["Red Team Data"]["Square"]["Bounding Box"]["X Right"],style0)
    ws.write(33,4+x,parsed["Red Team Data"]["Square"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(34,4+x,parsed["Red Team Data"]["Square"]["Area"],style0)
    ws.write(35,4+x,parsed["Red Team Data"]["Square"]["Orientation"],style0)
    ws.write(36,4+x,parsed["Red Team Data"]["Square"]["Aspect Ratio"],style0)
    ws.write(37,4+x,parsed["Red Team Data"]["Square"]["Nb Holes"],style0)
    ws.write(38,4+x,parsed["Red Team Data"]["Triangle"]["Object Center"]["X"],style0)
    ws.write(39,4+x,parsed["Red Team Data"]["Triangle"]["Object Center"]["Y"],style0)
    ws.write(40,4+x,parsed["Red Team Data"]["Triangle"]["Bounding Box"]["X Left"],style0)
    ws.write(41,4+x,parsed["Red Team Data"]["Triangle"]["Bounding Box"]["Y Top"],style0)
    ws.write(42,4+x,parsed["Red Team Data"]["Triangle"]["Bounding Box"]["X Right"],style0)
    ws.write(43,4+x,parsed["Red Team Data"]["Triangle"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(44,4+x,parsed["Red Team Data"]["Triangle"]["Area"],style0)
    ws.write(45,4+x,parsed["Red Team Data"]["Triangle"]["Orientation"],style0)
    ws.write(46,4+x,parsed["Red Team Data"]["Triangle"]["Aspect Ratio"],style0)
    ws.write(47,4+x,parsed["Red Team Data"]["Triangle"]["Nb Holes"],style0)
    ws.write(48,4+x,parsed["Blue Team Data"]["Circle"]["Object Center"]["X"],style0)
    ws.write(49,4+x,parsed["Blue Team Data"]["Circle"]["Object Center"]["Y"],style0)
    ws.write(50,4+x,parsed["Blue Team Data"]["Circle"]["Bounding Box"]["X Left"],style0)
    ws.write(51,4+x,parsed["Blue Team Data"]["Circle"]["Bounding Box"]["Y Top"],style0)
    ws.write(52,4+x,parsed["Blue Team Data"]["Circle"]["Bounding Box"]["X Right"],style0)
    ws.write(53,4+x,parsed["Blue Team Data"]["Circle"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(54,4+x,parsed["Blue Team Data"]["Circle"]["Area"],style0)
    ws.write(55,4+x,parsed["Blue Team Data"]["Circle"]["Orientation"],style0)
    ws.write(56,4+x,parsed["Blue Team Data"]["Circle"]["Aspect Ratio"],style0)
    ws.write(57,4+x,parsed["Blue Team Data"]["Circle"]["Nb Holes"],style0)
    ws.write(58,4+x,parsed["Blue Team Data"]["Square"]["Object Center"]["X"],style0)
    ws.write(59,4+x,parsed["Blue Team Data"]["Square"]["Object Center"]["Y"],style0)
    ws.write(60,4+x,parsed["Blue Team Data"]["Square"]["Bounding Box"]["X Left"],style0)
    ws.write(61,4+x,parsed["Blue Team Data"]["Square"]["Bounding Box"]["Y Top"],style0)
    ws.write(62,4+x,parsed["Blue Team Data"]["Square"]["Bounding Box"]["X Right"],style0)
    ws.write(63,4+x,parsed["Blue Team Data"]["Square"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(64,4+x,parsed["Blue Team Data"]["Square"]["Area"],style0)
    ws.write(65,4+x,parsed["Blue Team Data"]["Square"]["Orientation"],style0)
    ws.write(66,4+x,parsed["Blue Team Data"]["Square"]["Aspect Ratio"],style0)
    ws.write(67,4+x,parsed["Blue Team Data"]["Square"]["Nb Holes"],style0)
    ws.write(68,4+x,parsed["Blue Team Data"]["Triangle"]["Object Center"]["X"],style0)
    ws.write(69,4+x,parsed["Blue Team Data"]["Triangle"]["Object Center"]["Y"],style0)
    ws.write(70,4+x,parsed["Blue Team Data"]["Triangle"]["Bounding Box"]["X Left"],style0)
    ws.write(71,4+x,parsed["Blue Team Data"]["Triangle"]["Bounding Box"]["Y Top"],style0)
    ws.write(72,4+x,parsed["Blue Team Data"]["Triangle"]["Bounding Box"]["X Right"],style0)
    ws.write(73,4+x,parsed["Blue Team Data"]["Triangle"]["Bounding Box"]["Y Bottom"],style0)
    ws.write(74,4+x,parsed["Blue Team Data"]["Triangle"]["Area"],style0)
    ws.write(75,4+x,parsed["Blue Team Data"]["Triangle"]["Orientation"],style0)
    ws.write(76,4+x,parsed["Blue Team Data"]["Triangle"]["Aspect Ratio"],style0)
    ws.write(77,4+x,parsed["Blue Team Data"]["Triangle"]["Nb Holes"],style0)
    #--------------------------------
    time.sleep(1)
    x=x+1
#---------------------------------
wb.save('SwarmField_Data.xls')

input("Process Complete. Press 'Enter' to end program.")
